import mongoose from 'mongoose';

const insurancePolicySchema = new mongoose.Schema({
  serial_number: { type: String },
  date: { type: String },
  insurance_company_name: { type: String },
  lob: { type: String },
  package_liability: { type: String },
  fuel_type: { type: String },
  customer_name: { type: String },
  mobile_number: { type: String },
  location: { type: String },
  registration_number: { type: String },
  vehicle_make: { type: String },
  vehicle_model: { type: String },
  cc_gvw: { type: String },
  bike_scooter: { type: String },
  year_of_manufacture: { type: String },
  engine_number: { type: String },
  chassis_number: { type: String },
  policy_number: { type: String },
  idv_sum_insured: { type: String },
  ncb: { type: String },
  risk_start_date: { type: String },
  risk_end_date: { type: String },
  od_premium: { type: String },
  tp_only_premium: { type: String },
  net: { type: String },
  gst: { type: String },
  total_premium: { type: String },
  rec_po_on: { type: String },
  rec_percentage: { type: String },
  rec_amount: { type: String },
  imd_percentage: { type: String },
  imd_amount: { type: String },
  mode_of_payout: { type: String },
  revenue: { type: String },
  revenue_percentage: { type: String },
  leader_name: { type: String },
  employee_name: { type: String },
  imd_name: { type: String },
  retailer_name: { type: String },
  payment_status: { type: String },
  policy_created_by: { type: String },
  dealer_agent: { type: String },
  posp_referral: { type: String },
  remark: { type: String },
  original_file_url: { type: String },
  source_file: { type: String, default: '' },
  createdAt: { type: Date, default: Date.now }
}, { collection: 'insurance_policies' });

export default mongoose.model('InsurancePolicy', insurancePolicySchema);
